version: '3.8'

services:
  # Layanan WAHA (WhatsApp HTTP API)
  waha:
    image: devlikeapro/waha
    container_name: pitstop_waha
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_SECRET_KEY=${WAHA_API_KEY} # Menggunakan kunci dari .env
    volumes:
      - ./waha_data:/root/.waha/data

  # Layanan n8n (Automation Platform)
  n8n:
    image: n8nio/n8n
    container_name: pitstop_n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - GENERIC_GEMINI_API_KEY=${GEMINI_API_KEY} # Kunci Gemini
      # Mengaktifkan Midtrans sebagai Credential
      - N8N_CREDENTIAL_MIDTRANS_BASIC_AUTH_SERVER_KEY=${MIDTRANS_SERVER_KEY}
    volumes:
      - ./n8n_data:/home/node/.n8n
    links:
      - waha

networks:
  default:
    name: pitstop-network